# Point at any base image that you find suitable to extend.
#FROM stateoftheartio/qt6:6.6-wasm-aqt
FROM reivilo1234/qt-webassembly-cmake:qt5.15-em1.39.8

RUN apt install -y git

ENTRYPOINT ["/bin/bash", "-c"]
